name: Silabs GitHub Actions Demo
run-name: ${{github.actor}} has started a workflow run
on:
  push:
    branches:
      - workflow/test

jobs:
  test_java_job:
    name: test java setup
    runs-on: ubuntu-24.04
    steps:
      - name: Setup java
        uses: actions/setup-java@v5 # At Least a JRE version 17 is needed to run SLC-CLI (corretto is recommended in docs)
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Verify java
        run: |
          set -euo pipefail
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          readlink -f "$(which java)"
      - name: Download and install SLC-CLI
        run: |
          set -euo pipefail
          curl --location --silent --show-error --output /tmp/slc.zip "https://www.silabs.com/documents/public/software/slc_cli_linux.zip"
          unzip -q -d /opt/ /tmp/slc.zip
          chmod +x /opt/slc_cli/slc
          echo "/opt/slc_cli" >> "$GITHUB_PATH"
      - name: Verify SLC CLI installation
        run: |
          set -euo pipefail
          which slc
          echo "SLC CLI version $(slc --version)"
          




