name: Silabs GitHub Actions Demo
run-name: ${{github.actor}} has started a workflow run
on:
  push:
    branches:
      - workflow/test

jobs:
  test_java_job:
    name: test java setup
    runs-on: ubuntu-24.04
    steps:
      - name: Setup java
        uses: actions/setup-java@v5 # At Least a JRE version 17 is needed to run SLC-CLI (corretto is recommended in docs)
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: verify java
        run: |
          set -e
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          readlink -f "$(which java)"



