name: Silabs GitHub Actions Demo
run-name: ${{github.actor}} has started a workflow run
# on:
#   push:
#     branches:
#       - workflow/test
on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: 'selected sdk'
        required: true
        type: choice
        options: # these options need to match the version substring in the sdk download url
          - v2025.6.2
          - v2025.6.1
          - v2025.6.0
          - v2024.12.3
          - v2024.12.2
          - v2024.12.1
          - v2024.12.0
      selected_examples:
        description: 'selected examples, comma seperated or leave empty to select all'
        type: string
      selected_boards:
        description: 'selected boards, comma seperated or leave empty to select all'
        type: string

jobs:
  build_apps:
    env:
      ARM_GCC_DIR: /opt/arm-toolchain
      SDK_DIR: /opt/simplicity-sdk
      APPS_TEMPLATE_DIR: ${{ github.workspace }}/bluetooth_stack_features
      CI_PIPELINE_DIR: ${{ github.workspace }}/ci
      APPS_OUTPUT_DIR: /tmp/output/
    name: build_apps
    runs-on: ubuntu-24.04 # Runner info https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
    steps:
      - name: Setup java
        uses: actions/setup-java@v5 # At Least a JRE version 21 is needed to run SLC-CLI (corretto is recommended in docs)
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Verify java
        run: |
          set -euo pipefail
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          which java
          readlink -f "$(which java)"
      - name: Download and install SLC-CLI
        run: |
          set -euo pipefail
          curl --location --silent --show-error --output /tmp/slc.zip "https://www.silabs.com/documents/public/software/slc_cli_linux.zip"
          unzip -q -d /opt/ /tmp/slc.zip
          chmod +x /opt/slc_cli/slc
          echo "/opt/slc_cli" >> "$GITHUB_PATH"
      - name: Verify SLC CLI installation
        run: |
          set -euo pipefail
          which slc
          echo "SLC CLI version $(slc --version)"
      - name: Install toolchain #Arm GNU Toolchain 12.2.rel1-x86_64-arm-none-eabi
        run: |
          set -euo pipefail
          mkdir -p $ARM_GCC_DIR
          curl --location --silent --show-error --output /tmp/gcc.tar.xz "https://developer.arm.com/-/media/files/downloads/gnu/12.2.rel1/binrel/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi.tar.xz?rev=7bd049b7a3034e64885fa1a71c12f91d&revision=7bd049b7-a303-4e64-885f-a1a71c12f91d&hash=B698685C08AD15D3FD8B1BF2DB28D282"
          tar -xJf /tmp/gcc.tar.xz -C $ARM_GCC_DIR --strip-components=1
          echo "$ARM_GCC_DIR/bin" >> "$GITHUB_PATH"
      - name: Verifiy toolchain
        run: |
          set -euo pipefail
          arm-none-eabi-gcc --version
      - name: Download SDK # Currently downloading from Public Git repo (soon to be deprecated site)
        run: |
          set -euo pipefail
          mkdir $SDK_DIR
          curl --location --silent --show-error --output /tmp/simplicity-sdk.zip "https://github.com/SiliconLabs/simplicity_sdk/releases/download/${{inputs.sdk_version}}/simplicity-sdk.zip"
          unzip -q -d $SDK_DIR /tmp/simplicity-sdk.zip
      - name: SLC-CLI config for SDK and toolchain
        run: |
          set -euo pipefail
          slc signature trust --sdk=$SDK_DIR
          slc configuration --sdk=$SDK_DIR --gcc-toolchain=$ARM_GCC_DIR
      - name: pulling bluetooth_stack_features repo # Currently pulling from Public Git repo (soon to be deprecated site)
        uses: actions/checkout@v6
        with:
          repository: SiliconLabs/bluetooth_stack_features
          path: ${{env.APPS_TEMPLATE_DIR}}
      - name: pulling CI pipeline repo
        uses: actions/checkout@v6
        with: 
          repository: silabs-mehdi/GithubActionsTesting
          path: ${{env.CI_PIPELINE_DIR}}
      - name: build apps
        run: |
          set -euo pipefail
          mkdir $APPS_OUTPUT_DIR
          python3 ${{env.CI_PIPELINE_DIR}}/build_sample_app.py ${{env.APPS_TEMPLATE_DIR}} ${{inputs.selected_examples}} ${{inputs.selected_boards}} ${{env.APPS_OUTPUT_DIR}}
      - name: verify generateion folder
        run: |
          set -euo pipefail
          ls -R ${{env.APPS_OUTPUT_DIR}}
      # - name: build one app test
      #   run: |
      #     set -euo pipefail
      #     which cmake
      #     slc generate -p $APPS_TEMPLATE_DIR/advertising/advertising_manufacturer_specific_data/SimplicityStudio/soc_advertising_manufacturer_specific_data.slcp -d $APPS_BUILD_DIR/soc_advertising_manufacturer_specific_data --with brd4180a --output-type=cmake --new-project 
      #     cd $APPS_BUILD_DIR/soc_advertising_manufacturer_specific_data/soc_advertising_manufacturer_specific_data_cmake
      #     cmake --preset project 
      #     cmake --build --preset default_config
      #     ls $APPS_BUILD_DIR/soc_advertising_manufacturer_specific_data/soc_advertising_manufacturer_specific_data_cmake/build/default_config
      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries & logs
          path: ${{env.APPS_OUTPUT_DIR}}
      # - name: upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: binaries
      #     path: ${{env.APPS_BUILD_DIR}}/soc_advertising_manufacturer_specific_data/soc_advertising_manufacturer_specific_data_cmake/build/default_config
            




          




